### PR TITLE
Use threads to add and remove hosts to/from aggregate

### PR DESCRIPTION
**Pull request by AnishReddyRavula**
use threads to add or remove each host in a respective thread

### CODE REVIEW

**Review by Mark-Powers — APPROVED** [review]
This looks good to me! @msherman64 Is it possible to fake hypervisors on UC dev so this can be tested with a larger number of nodes?

**Review by msherman64 — COMMENTED** [review]
this also looks ok to me.

It's not strictly necessary, but I would be interested in what happens when 1 of a set of hosts fails to be moved to the new aggregate?

(e.g. alredy in aggregate, nova api too busy, etc). Is it possible to have a unit test for this that injects an exception?

**Comment by msherman64** [comment]
> This looks good to me! @msherman64 Is it possible to fake hypervisors on UC dev so this can be tested with a larger number of nodes?

Yes, but be careful so that we can undo those changes if needed. Preference is to use devstack or dev-in-a-box for that kind of testing, just because it's a constant battle to restore uc_dev to a sane state

**Review by msherman64 — APPROVED** [review]

**Comment by AnishReddyRavula** [comment]
> (e.g. alredy in aggregate, nova api too busy, etc). Is it possible to have a unit test for this that injects an exception?

Looks like there are already testcases for this - https://github.com/ChameleonCloud/blazar/blob/chameleoncloud/xena/blazar/tests/utils/openstack/test_nova.py#L316

**Comment by AnishReddyRavula** [comment]
When 100 hosts are added to a lease with and without this change in devstack, blazer took 1 minute without threads and 10 seconds with threads. 
Got these numbers from looking at timestamps in blazar logs.

**Pull request merged**
