### PR TITLE
Restore lease status on update

### PR DESCRIPTION
**Pull request by Mark-Powers**
This restores the lease status using a list types. Additionally, it fixes a bug with updating a lease.

### CODE REVIEW

**Comment by diurnalist** [comment]
Is this all part of one logical patch / should it be one commit?

**Review by diurnalist — APPROVED** [review]
LGTM!

**Comment by Mark-Powers** [comment]
> Is this all part of one logical patch / should it be one commit?

This could be made two, would you prefer that? They are related however, since updating a lease is bugged from the CLI (as far as I can tell) without commit `4b7e35f`.

**Comment by diurnalist** [comment]
I don't really mind, more of a question of it it's more confusing when comparing history to upstream later. Mostly concerned w/ commits matching commits that are (hopefully!) landing upstream.

**Pull request merged**
