### PR TITLE
Nova endpoint override

### PR DESCRIPTION
**Pull request by codyhammock**
This enables setting the endpoint_override in the nova section of the config file.

### CODE REVIEW

**Comment by codyhammock** [comment]
Yes, exactly

**Comment by priteau** [comment]
@codyhammock If the goal is simply to use the Nova internal API endpoint instead of the public one, you could add support for setting `endpoint_type` and pass it the value `internalURL`. This way it is one less thing to customize in each deployment.

However, if the internal API endpoint URL is also different and you want to customize it, this looks good.

**Comment by priteau** [comment]
Did you test what happens if `endpoint_override` is not set in the configuration file though?

**Comment by codyhammock** [comment]
Yes, I performed the test and it behaved as expected.

**Pull request merged**
